### ISSUE TITLE
[Discussion] Labeled data file structure

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/open-digger#686]
As new labeled data will come into the project for analysis, we need to decide how to store the data into OpenDigger.

Right now, we will have several label category like: region, company, community, foundation/incubator, tech category.

So the structure may have 3 layers: category type - label name - data, the file structure will be:

'|-label_data
'|--company
'|----alibaba
'|----microsoft
'|----tencent
'|----baidu
'|--region
'|----china
'|--community
'|----dubbo
'|----Paddle
'|--foundation_incubator
'|----Aapche
'|----CNCF
'|----mulan
'|--tech_category
'|----database

Is this a solution or anyone has better ideas about this?

**Comment by wengzhenjie** [comment]
I have a problem. When this issue will be sloved? I need these configs to query some data now. Even though there are some yaml config for me to parse, I am afraid of these configs will change. If I use current configs, there will be a problem for future which may lead my query invalid.

**Comment by wengzhenjie** [comment]
Another problem, could these configs upload to oss by github ci? Sometimes, the network is in bad shape.Using `git clone` to get configs may be not good.

**Comment by bifenglin** [comment]
I think ,it's better if we divid different lables into diffrent files.

**Comment by frank-zsy** [comment]
That's why I open this issue, we need to discuss about this now.

And if we decide the file structure of the labeled data, we can upload the files to OSS by CI of course.

> I have a problem. When this issue will be sloved? I need these configs to query some data now. Even though there are some yaml config for me to parse, I am afraid of these configs will change. If I use current configs, there will be a problem for future which may lead my query invalid.

**Comment by frank-zsy** [comment]
According to the design, all labeled data will save into different files.

> I think ,it's better if we divid different labels into different files.

**Comment by frank-zsy** [comment]
And we also need the labels can have a multi layer structure which means one label can contain another or more labels.

This will be very useful under following situation:
- Alibaba label contains Dubbo and Flink community.
- COSS label contains PingCAP, Vesoft and etc.

There are lots of this kind of needs and with multi layer label structure, we will only need to maintain repos and orgs for certain label in one place.

**Comment by alibaba-oss** [comment]
I also think it’s important to show open source project name instead several repos of one project when it comes to top projects rank.

**Comment by frank-zsy** [comment]
The purpose for structural configuration is to support multi layer embed and any label we want to aggegate data for repos and orgs.

So I propose a solution for the issue. We can use `github_repo` and `github_org` as elemental items and add a `group` element to group items. `github_repo` and `github_org` are lists of repo ids or org ids on GitHub and `group` contains a `name` property for identity and `type` property which indicate the type of the group like `company` or `project`. And `group` can also contain `github_repo` and `github_org` property and another `group` property which enable it to embed more data.

I can give an example like below:

xlab.yaml
``` yaml
name: X-lab
type: group
group:
  - OpenDigger
  - OpenGalaxy
  - Hypertrons
github_org:
  - 49427213 # X-lab2017
```

open_digger.yaml
``` yaml
name: OpenDigger
type: Project
github_repo:
  - 288431943 # X-lab2017/open-digger
```

open_galaxy.yaml
``` yaml
name: OpenGalaxy
type: Project
github_repo:
  - 428629051 # X-lab2017/open-galaxy
  - 439244862 # X-lab2017/open-galaxy-backend
```

hypertrons.yaml
``` yaml
name: Hypertrons
type: project
github_org:
  - 57651122 # hypertrons
```

Under this design, we can have any depth in the struct and quite flexible. In the downstream process we can use `type` to aggregate data.
